/**
 * Writes supabase/seed.sql from src/lib/data/seed.ts so the database starts
 * with the same catalogue as the storefront.
 *
 *   node scripts/generate-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { collections, journal, products, reviews } from "../src/lib/data/seed.ts";

const q = (v: unknown) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (v: string[]) => `array[${v.map(q).join(",")}]::text[]`;

const out: string[] = ["-- Generated by scripts/generate-seed-sql.ts. Safe to re-run (upserts).", "begin;"];

collections.forEach((c, i) =>
  out.push(
    `insert into collections (slug, name, blurb, image, accent, position) values (${q(c.slug)}, ${j(c.name)}, ${j(c.blurb)}, ${q(c.image)}, ${q(c.accent)}, ${i})
on conflict (slug) do update set name = excluded.name, blurb = excluded.blurb, image = excluded.image, accent = excluded.accent, position = excluded.position;`,
  ),
);

for (const p of products) {
  out.push(`insert into products (slug, collection_id, status, name, short, description, details, options, colors, tags, shipping, pairs_with, wall_piece, food_safe, hidden, bestseller_rank, created_at)
values (${q(p.slug)}, (select id from collections where slug = ${q(p.collection)}), 'active', ${j(p.name)}, ${j(p.short)}, ${j(p.description)}, ${j(p.details)}, ${j(p.options)}, ${arr(p.colors)}, ${arr(p.tags)}, ${q(p.shipping)}, ${arr(p.pairsWith)}, ${!!p.wallPiece}, ${!!p.foodSafe}, ${!!p.hidden}, ${p.bestseller}, ${q(p.createdAt)})
on conflict (slug) do update set collection_id = excluded.collection_id, name = excluded.name, short = excluded.short, description = excluded.description, details = excluded.details, options = excluded.options, colors = excluded.colors, tags = excluded.tags, shipping = excluded.shipping, pairs_with = excluded.pairs_with, wall_piece = excluded.wall_piece, food_safe = excluded.food_safe, hidden = excluded.hidden, bestseller_rank = excluded.bestseller_rank;`);
  out.push(`delete from product_media where product_id = (select id from products where slug = ${q(p.slug)});`);
  p.images.forEach((url, i) =>
    out.push(`insert into product_media (product_id, kind, url, position) values ((select id from products where slug = ${q(p.slug)}), 'image', ${q(url)}, ${i});`),
  );
  p.variants.forEach((v, i) =>
    out.push(`insert into variants (id, product_id, sku, options, price, compare_at, stock, image_index, position)
values (${q(v.id)}, (select id from products where slug = ${q(p.slug)}), ${q(v.sku)}, ${j(v.options)}, ${v.price}, ${v.compareAt ?? "null"}, ${v.stock}, ${v.image ?? "null"}, ${i})
on conflict (id) do update set sku = excluded.sku, options = excluded.options, price = excluded.price, compare_at = excluded.compare_at, stock = excluded.stock, image_index = excluded.image_index, position = excluded.position;`),
  );
}

out.push("delete from reviews where order_id is null and author in (" + reviews.map((r) => q(r.author)).join(",") + ");");
for (const r of reviews) {
  out.push(`insert into reviews (product_id, author, country, rating, title, body, photo, status, featured, reply, created_at)
values ((select id from products where slug = ${q(r.productSlug)}), ${q(r.author)}, ${q(r.country)}, ${r.rating}, ${q(r.title)}, ${q(r.body)}, ${q(r.photo)}, 'approved', ${!!r.featured}, ${q(r.reply)}, ${q(r.date)});`);
}

for (const p of journal) {
  out.push(`insert into journal_posts (slug, status, title, excerpt, cover, category, blocks, author, reading_minutes, publish_at)
values (${q(p.slug)}, 'published', ${j(p.title)}, ${j(p.excerpt)}, ${q(p.cover)}, ${j(p.category)}, ${j(p.blocks)}, ${q(p.author)}, ${p.readingMinutes}, ${q(p.date)})
on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, cover = excluded.cover, category = excluded.category, blocks = excluded.blocks, reading_minutes = excluded.reading_minutes;`);
}

out.push(`insert into discounts (code, kind, value, min_spend) values
  ('WELCOME10', 'percent', 10, null), ('SARDINHA5', 'fixed', 500, 4000), ('FREESHIP', 'free_shipping', 0, 3000)
on conflict (code) do nothing;`);
out.push(`insert into gift_cards (code, initial_value, balance, expires_at) values ('GIFT-DEMO-2026', 2500, 2500, now() + interval '2 years') on conflict (code) do nothing;`);
out.push(`insert into settings (key, value) values
  ('announcement', ${j({ en: "Free shipping in Portugal over €60 · Handmade in Portugal", pt: "Portes grátis em Portugal acima de 60 € · Feito à mão em Portugal" })}),
  ('hero', ${j({ image: "/lifestyle/hero.svg", title: { en: "Little pieces of Portuguese sunshine", pt: "Pequenos pedaços de sol português" } })})
on conflict (key) do nothing;`);
out.push("commit;");

writeFileSync("supabase/seed.sql", out.join("\n\n") + "\n");
console.log(`seed.sql: ${products.length} products, ${reviews.length} reviews, ${journal.length} posts`);
